ProjectHub/ProjectHub/Controllers/ProjectController.cs
using ProjectHub.Models;
using ProjectHub.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectHub.Controllers
{
    public class ProjectController : Controller
    {
	    private ProjectService _projectService;
        private TopicService _topicService;
        private PostService _postService;

	    public ProjectController()
	    {
		    _projectService = new ProjectService();
            _topicService = new TopicService();
            _postService = new PostService();
	    }

	    public ActionResult Index ()
        {

	        var model = _projectService.GetProjects();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new ProjectCreateViewModel();

           
            var TopicList = _topicService.GetTopics();
            model.projectModel = new ProjectModel();
            model.availableTopics = TopicList;

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ProjectCreateViewModel model, string[] checkedTopics)
        {
            var el = new ElasticService();
            List<TopicModel> topicList = new List<TopicModel>();

            foreach (var items in checkedTopics)
            {
                TopicModel topic = el.GetClient().Get<TopicModel>(items).Source;
                topicList.Add(topic);
            }

            model.projectModel.Topics = topicList;
            el.IndexDocument(model.projectModel);
            return RedirectToAction("Index");
        }

        [HttpGet] 
        public ActionResult Details(string Id)
        {
	        var model = _projectService.GetProject(Id);
            model.Posts = _postService.GetPostsForProject(model.Id).ToList();
            
            return View(model);
        }
    }

	
}

ProjectHub/ProjectHub/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectHub.Models;
using ProjectHub.Models.Dto;
using ProjectHub.Service;

namespace ProjectHub.Controllers
{
    public class TopicController : Controller
    {
        
	    private TopicService _topicService;
	    private PostService _postService;

	    public TopicController()
        {
	        _topicService = new TopicService();
            _postService = new PostService();
		    

        }

        // GET: Topic
        public ActionResult Index()
        {
	        var model = _topicService.GetTopics();
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new TopicModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(TopicModel topic)
        {
			var elasticService = new ElasticService();
			elasticService.IndexDocument(topic);
            
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(string id)
        {
			var topic = _topicService.GetTopic(id);

            var model = new TopicDetailDto
            {
                Name = topic.Name,
                Description = topic.Description,
                Posts = _postService.GetPostsForTopic(id)
            };

            return View(model);
        }

        //public IEnumerable<PostModel>  GetListOfPostsForTopic(string topicID)
        //{
        //    var cl = _elasticService.GetClient();
        //    var res = cl.Search<PostModel>(mmd => mmd.Query(mq => mq.Term(qmt => qmt.Id,topicID) ));
        //    var posts = res.Hits.Select(hit => {
        //                                           hit.Source.Id = hit.Id;
        //                                           return hit.Source;
        //    }).ToList();
        //    return posts;
        //}

        public ActionResult Edit()
        {
            return View(new TopicModel());
        }

        [HttpPost]
        public ActionResult Edit(TopicModel topic)
        {

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete()
        {
            return View(new TopicModel());
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            return RedirectToAction(nameof(Index));
        }

    }
}

ProjectHub/ProjectHub/Views/Project/Create.cshtml
@model ProjectHub.Models.ProjectCreateViewModel

@{
    ViewBag.Title = "Create Awesome Project";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Project", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.projectModel.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.projectModel.Name, new { @class = "form-control" })
        </div>
    </div>

    foreach (var topic in Model.availableTopics)
    {
        <span>
            <input style="display:inline-block;" type="checkbox" class="checkbox" name="checkedTopics" value="@topic.Id" id="@topic.Id" />
            <label for="@topic.Name">@topic.Name</label>
        </span>
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add project" />
        </div>
    </div>
}

ProjectHub/ProjectHub/Views/Project/Details.cshtml
@model ProjectHub.Models.ProjectModel

@{
    ViewBag.Title = Model.Name;
}

<h2>@ViewBag.Title</h2>

<hr />
<h3>Topics</h3>

@if (Model.Topics != null)
{
    foreach (var topics in Model.Topics)
    {
        <p>@Html.ActionLink("#"+ topics.Name, "Details", "Topic", new { id = topics.Id }, null)</p>
    }
}


<hr />
<h3>Posts</h3>

@if(Model.Posts != null)
{
    @Html.DisplayFor(m => m.Posts)
}

<div style="padding-top:15px;">
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectHub/ProjectHub/Views/Project/Index.cshtml
@model List<ProjectHub.Models.ProjectModel>

@{
    ViewBag.Title = "Projectlist";
}



<a style="float:right; margin-bottom:15px; padding:20px 35px; background:#eee; color:black;text-decoration:none;" href="/Project/Create">Create new project</a>

<h2 style="padding-bottom:20px;">@ViewBag.Title</h2>



@foreach(var project in Model)
{
    
    <p>@project.Name [@project.Id] @Html.ActionLink("Details", "Details", new { id = project.Id })</p>
    
    <hr />
}